# -*- coding: utf-8 -*-
"""mi_candidate_0.1_210514.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/github/luzydata/micandidate/blob/main/mi_candidate_0_1_210514.ipynb
"""

import requests
import pandas as pd

BASE = 'https://e7f1hlosbh.execute-api.us-east-2.amazonaws.com/staging/'

auth_header = {
	'Authorization': 'eyJraWQiOiJQNU9BRVwvbWwwUTdHRko0WVl0aVp6c3ZiXC9QU1JhXC9pbFZiOUNCeVdDSFpRPSIsImFsZyI6IlJTMjU2In0.eyJhdF9oYXNoIjoiWHFCZzZHQUc2amY0eU1QWURuZWhoZyIsInN1YiI6IjllODY5ODA2LTZmNjgtNDhlNi1iNzhlLTk5ODI0MDEzNzAyNyIsImF1ZCI6IjZkYjZibGxsYWltMWVicW5lZm9lNjFibjlsIiwiZW1haWxfdmVyaWZpZWQiOnRydWUsImV2ZW50X2lkIjoiN2Y0MzAxOGMtZjAzOC00NTM1LTkxMjQtYWFkMmRkOTgxZDA5IiwidG9rZW5fdXNlIjoiaWQiLCJhdXRoX3RpbWUiOjE2MjE0MDI2NDksImlzcyI6Imh0dHBzOlwvXC9jb2duaXRvLWlkcC51cy1lYXN0LTIuYW1hem9uYXdzLmNvbVwvdXMtZWFzdC0yX0oxS0lzY3BoaCIsImNvZ25pdG86dXNlcm5hbWUiOiI5ZTg2OTgwNi02ZjY4LTQ4ZTYtYjc4ZS05OTgyNDAxMzcwMjciLCJleHAiOjE2MjE0MTcwNDksImlhdCI6MTYyMTQwMjY0OSwiZW1haWwiOiJ1cmRhaWJheWNAZ21haWwuY29tIn0.Yaa8dgVst9t13bZhFEQIF1SntdEwjN8qCSh8-nfkHS1IJh185EFAKUPKArBjZ0CVKGIY6y-SI_naPb580F7Xfo0lBikHV_tWjldCfC82d2F48qDALpWMUEGonat9-N88053isl0N5ee9c_X0G82VdepKpbyoBCd5qM0kS7q-ZB9wWgclslv8xRl-7CgBewwt6bBXku2Ainy-5R6VXV6n_gwJn9pWfJW9LRoU2pS43mBL0KB_wZiJk0ulOkFxrWCFSO2R6ckoZ3W0utAMLMOoLLOq1J7HEpZ3i20D7W5qdybhOh4TnxtBHSDaPTXKmj8qPog-nmK8u_VzoKuLkYUDSw'
}

print('-----------------------------------------------------------------------')
print('Getting areas')
response = requests.get(BASE + 'area', headers=auth_header, verify=True,  timeout=None)
print(response.json())
print('-----------------------------------------------------------------------')
# print('Getting an area')
# response = requests.get(BASE + 'area/123', headers=auth_header, verify=True,  timeout=None)
# print(response.json())
# print('-----------------------------------------------------------------------')
#
